"""empty message

Revision ID: 28676f969939
Revises: 7a89f30574c9
Create Date: 2020-01-18 17:48:25.691473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28676f969939'
down_revision = '7a89f30574c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'description')
    # ### end Alembic commands ###
