"""empty message

Revision ID: 397db1b0546e
Revises: e22bd29a32b9
Create Date: 2020-01-20 11:08:29.599775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397db1b0546e'
down_revision = 'e22bd29a32b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'sort_order')
    # ### end Alembic commands ###
